# Generated by Django 5.2.6 on 2026-02-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_orderitem_order_alter_cartitem_added_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=23)),
                ('town', models.CharField(max_length=24)),
                ('street_address', models.CharField(max_length=30)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('shipping_method', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='standard', max_length=23)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tracking_number', models.IntegerField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipmemt', to='orders.order')),
            ],
        ),
    ]
