# Generated by Django 5.2.6 on 2026-02-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Shipmemt', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('pickup', 'Store Pickup')], default='standard', max_length=23),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
