# Generated by Django 5.2.6 on 2026-03-18 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order'),
        ),
    ]
